### ISSUE TITLE
Error trying to import into javascript

### ISSUE THREAD

**Issue by bradlis7** [msumit/zxcvbn-rails#1]
I followed the first 2 steps in usage:

1. Add `gem 'zxcvbn-rails'` to Gemfile
2. Run `bundle install` (Found zxcvbn-rails 4.4.1)
3. Add `//= require zxcvbn` to application.js

Started the server fine, but go this message when trying to load the page:

```
couldn't find file 'zxcvbn' with type 'application/javascript'
```

**Comment by msumit** [comment]
Thanks @bradlis7 for reporting the issue. Found that there was a typo in `javascripts` folder name. Please uninstall gem and do a bundle install again and let me know if that works or not.

**Comment by bradlis7** [comment]
That works 👍
