### ISSUE TITLE
File not found: zxcvbn.js.map

### ISSUE THREAD

**Issue by bradlis7** [msumit/zxcvbn-rails#2]
This is a minor issue, but the last line of the file contains a source map that is loaded if you open up dev console.

    //# sourceMappingURL=zxcvbn.js.map

I'd suggest either removing that line, or include the map file in the project. It doesn't break anything, just gives a 404 on the server.

**Comment by msumit** [comment]
Don't know whats `zxcvbn.js.map` file used for, anyway added in vendor to resolve the error. Thanks for reporting @bradlis7..

**Comment by bradlis7** [comment]
It is generated in the process of minification to allow for nicer debugging on the client side. Not absolutely necessary, but it's nice to have it.
